export const videos = [
  {
    id: "1",
    title: "Scammer Thought It Was Easy... Mike & Shellymaff Join Forces",
    category: "scam-baiting",
    views: "125K",
    timeAgo: "3 days ago",
    duration: "12:45",
    color: "#1a0a00",
  },
  {
    id: "2",
    title: "Scammer Falls Hard — Best Moments Compilation",
    category: "scam-baiting",
    views: "98K",
    timeAgo: "1 week ago",
    duration: "10:32",
    color: "#001a0a",
  },
  {
    id: "3",
    title: "Live Scam Calls Compilation — They Get Mad!",
    category: "live-calls",
    views: "210K",
    timeAgo: "2 weeks ago",
    duration: "26:19",
    color: "#0a001a",
  },
  {
    id: "4",
    title: "Secure Your Devices — Stop Being an Easy Target",
    category: "tech-tips",
    views: "75K",
    timeAgo: "3 weeks ago",
    duration: "8:47",
    color: "#001a1a",
  },
  {
    id: "5",
    title: "Scam Baiting Live — Epic Reactions",
    category: "live-calls",
    views: "163K",
    timeAgo: "1 month ago",
    duration: "31:02",
    color: "#1a1a00",
  },
  {
    id: "6",
    title: "Common Scams in 2024 — How to Stay Safe",
    category: "privacy-security",
    views: "87K",
    timeAgo: "1 month ago",
    duration: "31:02",
    color: "#0a0a1a",
  },
  {
    id: "7",
    title: "The Dark Web Explained — What You Need to Know",
    category: "privacy-security",
    views: "54K",
    timeAgo: "2 months ago",
    duration: "15:21",
    color: "#1a000a",
  },
  {
    id: "8",
    title: "I Exposed a Fake IRS Scammer Live on Stream",
    category: "scam-baiting",
    views: "312K",
    timeAgo: "2 months ago",
    duration: "22:08",
    color: "#001a00",
  },
  {
    id: "9",
    title: "Password Security in 2024 — Are You Safe?",
    category: "tech-tips",
    views: "41K",
    timeAgo: "3 months ago",
    duration: "9:55",
    color: "#0a1a00",
  },
];

export const categories = [
  { id: "all", label: "ALL" },
  { id: "scam-baiting", label: "SCAM BAITING" },
  { id: "tech-tips", label: "TECH TIPS" },
  { id: "privacy-security", label: "PRIVACY & SECURITY" },
  { id: "live-calls", label: "LIVE CALLS" },
];

export const products = [
  {
    id: "1",
    name: "Tribal Hoodie",
    price: 44.99,
    category: "apparel",
    color: "#1a0a00",
  },
  {
    id: "2",
    name: "Ghost Tee",
    price: 24.99,
    category: "apparel",
    color: "#001a0a",
  },
  {
    id: "3",
    name: "Shaman Snapback",
    price: 29.99,
    category: "hats",
    color: "#0a001a",
  },
  {
    id: "4",
    name: "Tribal Sticker Pack",
    price: 9.99,
    category: "stickers",
    color: "#001a1a",
  },
  {
    id: "5",
    name: "Ghost Logo Tee",
    price: 22.99,
    category: "apparel",
    color: "#1a1a00",
  },
  {
    id: "6",
    name: "Skull Beanie",
    price: 19.99,
    category: "accessories",
    color: "#0a0a1a",
  },
  {
    id: "7",
    name: "GhostShaman Patch",
    price: 7.99,
    category: "accessories",
    color: "#1a000a",
  },
  {
    id: "8",
    name: "Dad Hat",
    price: 24.99,
    category: "hats",
    color: "#001a00",
  },
];

export const merchCategories = [
  { id: "all", label: "ALL" },
  { id: "apparel", label: "APPAREL" },
  { id: "accessories", label: "ACCESSORIES" },
  { id: "hats", label: "HATS" },
  { id: "stickers", label: "STICKERS" },
];

export const tools = [
  {
    id: "1",
    title: "Scam Checklist",
    description: "A quick-access checklist to help you spot red flags and avoid scams before it's too late.",
    cta: "VIEW TOOL",
    icon: "checklist",
  },
  {
    id: "2",
    title: "Privacy Guides",
    description: "Step-by-step guides to protect your data and your identity from prying eyes.",
    cta: "VIEW GUIDES",
    icon: "shield",
  },
  {
    id: "3",
    title: "Security Tools",
    description: "Recommended tools to secure your devices and accounts against modern threats.",
    cta: "VIEW TOOLS",
    icon: "lock",
  },
  {
    id: "4",
    title: "Useful Links",
    description: "Important links and resources we trust and use — curated for the community.",
    cta: "VIEW LINKS",
    icon: "link",
  },
  {
    id: "5",
    title: "Scammer Database",
    description: "Known scammer numbers, emails, and tactics documented by the community.",
    cta: "VIEW DATABASE",
    icon: "database",
  },
  {
    id: "6",
    title: "Report a Scam",
    description: "Official reporting links for the FTC, FBI IC3, and other government agencies.",
    cta: "REPORT NOW",
    icon: "flag",
  },
];
